// setup:feature:demo

package demo

import (
	"fmt"
	"math/rand/v2"
	"sync"
	"time"
)

// ToastSeverity is the visual severity of a toast event.
type ToastSeverity string

// Toast severity levels.
const (
	ToastSuccess ToastSeverity = "success"
	ToastInfo    ToastSeverity = "info"
	ToastWarning ToastSeverity = "warning"
	ToastError   ToastSeverity = "error"
)

// AllToastSeverities lists the available severities in display order.
var AllToastSeverities = []ToastSeverity{ToastSuccess, ToastInfo, ToastWarning, ToastError}

// ToastSeverityMix names a preset distribution of severities.
type ToastSeverityMix string

// Severity mix presets.
const (
	ToastMixBalanced     ToastSeverityMix = "balanced"
	ToastMixWarningHeavy ToastSeverityMix = "warning-heavy"
	ToastMixErrorHeavy   ToastSeverityMix = "error-heavy"
	ToastMixSuccessOnly  ToastSeverityMix = "success-only"
)

// ToastEvent is a single toast event generated by the simulator.
type ToastEvent struct {
	Timestamp  time.Time     `json:"timestamp"`
	ID         string        `json:"id"`
	Title      string        `json:"title"`
	Body       string        `json:"body"`
	Source     string        `json:"source"`
	Severity   ToastSeverity `json:"severity"`
	DurationMS int           `json:"duration_ms"`
	Replayable bool          `json:"replayable"`
	Sticky     bool          `json:"sticky"`
}

// ToastLabSettings holds operator-controlled simulation parameters.
type ToastLabSettings struct {
	SeverityMix    ToastSeverityMix // severity distribution
	RateMS         int              // ms between ticks (100–5000)
	DismissDurMS   int              // auto-dismiss ms (1000–30000)
	StackSize      int              // max visible toasts (3–20)
	BurstSize      int              // toasts per burst (1–10)
	ReplayRecent   bool             // replay recent toasts on reconnect
}

// ToastLabStats tracks aggregate counters.
type ToastLabStats struct {
	Published int64
	Displayed int64
	Dismissed int64
	Dropped   int64
	Replayed  int64
}

// ToastLabLogEntry records a lifecycle action for the inspector.
type ToastLabLogEntry struct {
	Timestamp time.Time
	Action    string
}

// ToastLab wraps the shared state for the toast lab demo.
type ToastLab struct {
	eventLog []ToastEvent
	lifeLog  []ToastLabLogEntry
	settings ToastLabSettings
	stats    ToastLabStats
	mu       sync.RWMutex
	seq      int64
	paused   bool
}

// NewToastLab creates a lab with default settings.
func NewToastLab() *ToastLab {
	return &ToastLab{
		settings: ToastLabSettings{
			SeverityMix:  ToastMixBalanced,
			RateMS:       2000,
			DismissDurMS: 5000,
			StackSize:    8,
			BurstSize:    1,
			ReplayRecent: false,
		},
	}
}

// Settings returns a snapshot of current settings.
func (l *ToastLab) Settings() ToastLabSettings {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.settings
}

// UpdateSettings applies changes under write lock.
func (l *ToastLab) UpdateSettings(fn func(s *ToastLabSettings)) {
	l.mu.Lock()
	defer l.mu.Unlock()
	fn(&l.settings)
}

// Stats returns a snapshot of counters.
func (l *ToastLab) Stats() ToastLabStats {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.stats
}

// IncrDisplayed increments the displayed counter.
func (l *ToastLab) IncrDisplayed() {
	l.mu.Lock()
	l.stats.Displayed++
	l.mu.Unlock()
}

// IncrDismissed increments the dismissed counter.
func (l *ToastLab) IncrDismissed() {
	l.mu.Lock()
	l.stats.Dismissed++
	l.mu.Unlock()
}

// IncrDropped increments the dropped counter.
func (l *ToastLab) IncrDropped() {
	l.mu.Lock()
	l.stats.Dropped++
	l.mu.Unlock()
}

// IncrReplayed increments the replayed counter.
func (l *ToastLab) IncrReplayed() {
	l.mu.Lock()
	l.stats.Replayed++
	l.mu.Unlock()
}

// Paused returns whether the simulator is paused.
func (l *ToastLab) Paused() bool {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return l.paused
}

// TogglePause flips pause state and returns the new value.
func (l *ToastLab) TogglePause() bool {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.paused = !l.paused
	return l.paused
}

// SimTick generates one or more toast events based on current settings.
func (l *ToastLab) SimTick() []ToastEvent {
	l.mu.Lock()
	defer l.mu.Unlock()

	count := l.settings.BurstSize
	events := make([]ToastEvent, 0, count)

	titles := map[ToastSeverity][]string{
		ToastSuccess: {"Deploy succeeded", "Health check passed", "Backup complete", "Migration applied"},
		ToastInfo:    {"New user registered", "Config reloaded", "Scheduled job started", "Cache refreshed"},
		ToastWarning: {"High memory usage", "Slow query detected", "Certificate expiring", "Rate limit approaching"},
		ToastError:   {"Service unreachable", "Database timeout", "Auth failure", "Disk space critical"},
	}
	sources := []string{"api-gateway", "scheduler", "monitor", "deployer", "auth-service"}

	for range count {
		l.seq++
		sev := l.pickSeverity()
		titlePool := titles[sev]
		title := titlePool[rand.IntN(len(titlePool))]
		sticky := sev == ToastError && rand.IntN(4) == 0

		evt := ToastEvent{
			Timestamp:  time.Now().UTC(),
			ID:         fmt.Sprintf("toast-%d", l.seq),
			Title:      title,
			Body:       fmt.Sprintf("Event #%d from simulator", l.seq),
			Source:     sources[rand.IntN(len(sources))],
			Severity:   sev,
			DurationMS: l.settings.DismissDurMS,
			Replayable: l.settings.ReplayRecent,
			Sticky:     sticky,
		}
		events = append(events, evt)
		l.stats.Published++

		l.eventLog = append(l.eventLog, evt)
		if len(l.eventLog) > 50 {
			l.eventLog = l.eventLog[len(l.eventLog)-50:]
		}
	}

	return events
}

func (l *ToastLab) pickSeverity() ToastSeverity {
	r := rand.IntN(100)
	switch l.settings.SeverityMix {
	case ToastMixWarningHeavy:
		if r < 50 {
			return ToastWarning
		} else if r < 70 {
			return ToastError
		} else if r < 85 {
			return ToastInfo
		}
		return ToastSuccess
	case ToastMixErrorHeavy:
		if r < 50 {
			return ToastError
		} else if r < 70 {
			return ToastWarning
		} else if r < 85 {
			return ToastInfo
		}
		return ToastSuccess
	case ToastMixSuccessOnly:
		return ToastSuccess
	default: // balanced
		if r < 25 {
			return ToastSuccess
		} else if r < 50 {
			return ToastInfo
		} else if r < 75 {
			return ToastWarning
		}
		return ToastError
	}
}

// Emit generates a single toast with the given severity (for manual buttons).
func (l *ToastLab) Emit(sev ToastSeverity) ToastEvent {
	l.mu.Lock()
	defer l.mu.Unlock()

	l.seq++
	evt := ToastEvent{
		Timestamp:  time.Now().UTC(),
		ID:         fmt.Sprintf("toast-%d", l.seq),
		Title:      fmt.Sprintf("Manual %s toast", sev),
		Body:       fmt.Sprintf("Manually triggered event #%d", l.seq),
		Source:     "operator",
		Severity:   sev,
		DurationMS: l.settings.DismissDurMS,
		Replayable: l.settings.ReplayRecent,
		Sticky:     sev == ToastError,
	}
	l.stats.Published++

	l.eventLog = append(l.eventLog, evt)
	if len(l.eventLog) > 50 {
		l.eventLog = l.eventLog[len(l.eventLog)-50:]
	}
	return evt
}

// RecordLifecycle appends a lifecycle entry, keeping the last 50.
func (l *ToastLab) RecordLifecycle(action string) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.lifeLog = append(l.lifeLog, ToastLabLogEntry{
		Timestamp: time.Now().UTC(),
		Action:    action,
	})
	if len(l.lifeLog) > 50 {
		l.lifeLog = l.lifeLog[len(l.lifeLog)-50:]
	}
}

// LifecycleLog returns the recent lifecycle log.
func (l *ToastLab) LifecycleLog() []ToastLabLogEntry {
	l.mu.RLock()
	defer l.mu.RUnlock()
	out := make([]ToastLabLogEntry, len(l.lifeLog))
	copy(out, l.lifeLog)
	return out
}

// EventLog returns the recent event log.
func (l *ToastLab) EventLog() []ToastEvent {
	l.mu.RLock()
	defer l.mu.RUnlock()
	out := make([]ToastEvent, len(l.eventLog))
	copy(out, l.eventLog)
	return out
}

// ResetStats zeroes all counters.
func (l *ToastLab) ResetStats() {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.stats = ToastLabStats{}
}
